# VideoMAE Action Classification Configuration
# Configuration for fine-tuning VideoMAE on VideoBadminton_Dataset for action classification

# Model configuration
model:
  base_model: "MCG-NJU/videomae-base-finetuned-kinetics"  # Pre-trained VideoMAE model
  
# Data configuration
data:
  # Dataset path - directory containing action class folders
  dataset_path: "/home/ubuntu/Project/shuttle-sense/VideoBadminton_Dataset"
  
  # Video processing parameters
  window_size: 16  # Number of frames per video clip
  sample_rate: 2   # Frame sampling rate (take every N frames)
  frame_size: 224  # Input frame size (224x224)
  
  # Data split ratios
  train_ratio: 0.7   # 70% for training
  val_ratio: 0.15    # 15% for validation
  test_ratio: 0.15   # 15% for testing

# Training configuration
training:
  # Training parameters
  epochs: 10          # Small number for testing
  batch_size: 8      # Minimal batch size due to GPU memory
  learning_rate: 5e-6  # Lower learning rate for fine-tuning
  weight_decay: 0.01
  warmup_ratio: 0.1
  
  # Checkpointing
  checkpoint_dir: "models/checkpoints/action_classification"
  save_every: 1  # Save every epoch for testing
  
  # Early stopping
  early_stopping:
    enabled: true
    patience: 15
    monitor: "val_f1"  # Metric to monitor

# Evaluation configuration
evaluation:
  metrics: ["accuracy", "precision", "recall", "f1", "confusion_matrix"]
  
# Hardware configuration
hardware:
  device: "auto"  # auto, cuda, cpu
  mixed_precision: true  # Use automatic mixed precision
  gradient_checkpointing: true  # Save memory at cost of speed
  
# Logging configuration
logging:
  level: "INFO"
  log_file: "action_classification_training.log.2"
  
  # Weights & Biases integration
  use_wandb: false  # Set to true to enable W&B logging
  wandb_project: "shuttlesense-action-classification"
  wandb_entity: null  # Your W&B entity (username/team)
  
  # TensorBoard logging
  use_tensorboard: true
  tensorboard_dir: "logs/tensorboard/action_classification"

# Action Classes (18 badminton techniques)
action_classes:
  - "00_Short Serve"
  - "01_Cross Court Flight" 
  - "02_Lift"
  - "03_Tap Smash"
  - "04_Block"
  - "05_Drop Shot"
  - "06_Push Shot"
  - "07_Transitional Slice"
  - "08_Cut"
  - "09_Rush Shot"
  - "10_Defensive Clear"
  - "11_Defensive Drive"
  - "12_Clear"
  - "13_Long Serve"
  - "14_Smash"
  - "15_Flat Shot"
  - "16_Rear Court Flat Drive"
  - "17_Short Flat Shot"

# Model deployment
deployment:
  # Export configuration
  export_formats: ["pytorch", "onnx"]
  export_dir: "models/exported/action_classification_2"